version: '3.8'

services:
  backend:
    build: ./backappchat
    ports:
      - "3000:3000"
    volumes:
      - ./backappchat:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monreseau

  frontend:
    build: ./frontappchat
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    restart: unless-stopped
    networks:
      - monreseau

networks:
  monreseau:
    driver: bridge